name: fantacySports
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, res`pectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+43

environment:
  sdk: ">=2.7.0 <=3.0.2"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  flutter_pin_code_fields: ^1.1.0
  flutter_swiper: ^1.1.6
  carousel_pro: ^1.0.0
  percent_indicator: ^4.0.0
  flutter_countdown_timer: ^4.1.0
  razorpay_flutter: ^1.2.7
  fluttertoast: ^8.0.8
  flutter_braintree: ^2.0.0+1
  empty_widget: ^0.0.3
  fragment_navigate: ^1.2.0+2
  image_picker: ^0.8.4+10
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.4
  loading_animation_widget: ^1.1.0+3
  dio: ^4.0.4
  connectivity: ^3.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.4
  mime: ^1.0.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  flutter_facebook_login: ^3.0.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  sms_autofill: ^2.2.0
  webview_flutter: ^3.0.1
  new_version: ^0.3.0
  package_info_plus: ^1.4.0
  badges: ^2.0.2
  dio_cookie_manager: ^2.0.0
  cookie_jar: 3.0.1
  paytm_allinonesdk: ^1.1.5
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  uuid: 3.0.6
  carousel_slider: ^4.0.0
  cashfree_pg: ^2.0.10+30
  pull_to_refresh: ^2.0.0
  flutter_downloader: ^1.8.1
  path_provider: ^2.0.11
#  html: ^0.15.0
#  sms_otp_auto_verify: ^2.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - jsonFile/languagetext.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma_Regular_font.ttf
    - family: Alfa
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Trajan
      fonts:
        - asset: assets/fonts/TrajanPro.ttf
        - asset: assets/fonts/TrajanPro-Regular.ttf
        - asset: assets/fonts/TrajanPro-Bold.otf
    - family: verdana
      fonts:
        - asset: assets/fonts/verdana.ttf
        - asset: assets/fonts/verdana-bold.ttf
        - asset: assets/fonts/verdana-bold-italic.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Black.ttf
        - asset: assets/fonts/Cinzel-Bold.ttf
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-ExtraBold.ttf
        - asset: assets/fonts/Cinzel-Medium.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
